# Generated by Django 4.0.6 on 2022-08-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=200, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=200, null=True)),
                ('birthday', models.DateField(null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('kakao_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
