# Generated by Django 4.0.6 on 2022-08-03 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.URLField(max_length=600)),
            ],
            options={
                'db_table': 'airlines',
            },
        ),
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.airline')),
            ],
            options={
                'db_table': 'airplanes',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'discounts',
            },
        ),
        migrations.CreateModel(
            name='FlightDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.discount')),
            ],
            options={
                'db_table': 'flight_details',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('image', models.URLField(max_length=600, null=True)),
                ('latitude', models.CharField(max_length=100, null=True)),
                ('longitude', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('conuntry', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'passengers',
            },
        ),
        migrations.CreateModel(
            name='PassengerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'passenger_types',
            },
        ),
        migrations.CreateModel(
            name='SeatClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'seat_classes',
            },
        ),
        migrations.CreateModel(
            name='Ticketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=300)),
                ('flight_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.flightdetail')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.passenger')),
            ],
            options={
                'db_table': 'ticketings',
            },
        ),
        migrations.CreateModel(
            name='FlightInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('normal_remainning_seats', models.IntegerField()),
                ('business_remainning_seats', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.airplane')),
                ('arrival_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_flight_informations', to='tickets.location')),
                ('departure_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_flight_informations', to='tickets.location')),
            ],
            options={
                'db_table': 'flight_informations',
            },
        ),
        migrations.AddField(
            model_name='flightdetail',
            name='flight_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.flightinformation'),
        ),
        migrations.AddField(
            model_name='flightdetail',
            name='passenger_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.passengertype'),
        ),
        migrations.AddField(
            model_name='flightdetail',
            name='seat_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.seatclass'),
        ),
    ]
