# Generated by Django 4.0.6 on 2022-08-03 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightinformation',
            old_name='business_remainning_seats',
            new_name='business_remaining_seats',
        ),
        migrations.RenameField(
            model_name='flightinformation',
            old_name='normal_remainning_seats',
            new_name='normal_remaining_seats',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='conuntry',
            new_name='country',
        ),
    ]
